// All shop products live here for now.
// Later this will move to a real database — for the prototype it's one file,
// so adding or editing a product means editing this list only.

export function formatRWF(amount) {
  return "RWF " + amount.toLocaleString("en-US");
}

export const products = [
  {
    slug: "tecno-spark-20",
    title: 'Tecno Spark 20 — 6.6" HD+ 90Hz, 128GB + 8GB RAM, Dual SIM',
    brand: "Tecno",
    category: "phones",
    art: "phone",
    price: 145000,
    oldPrice: 165000,
    off: "-12%",
    stars: "★★★★☆",
    count: 214,
    stock: 23,
    sold: 89,
    blurb: [
      "The Tecno Spark 20 gives you a big, smooth 90Hz screen, a 50MP camera that performs in low light, and a battery that comfortably lasts a full day — at a price that makes sense.",
      "This unit is official Rwanda stock with a 12-month warranty, sealed in the box with charger and case included. Kinyarwanda, English and French supported out of the box.",
    ],
    highlights: [
      ["Display", '6.6" HD+ IPS, 90Hz refresh rate'],
      ["Memory", "128GB storage · 8GB RAM (extendable)"],
      ["Camera", "50MP main · 32MP selfie with dual flash"],
      ["Battery", "5,000mAh · 18W fast charging"],
      ["Warranty", "12 months, official Tecno Rwanda"],
    ],
    specs: [
      ["Display", '6.6" HD+ IPS, 90Hz, 720 × 1612'],
      ["Processor", "MediaTek Helio G85, octa-core"],
      ["Storage / RAM", "128GB / 8GB (up to 16GB extended)"],
      ["Rear camera", "50MP main + AI lens, quad flash"],
      ["Front camera", "32MP with dual flash"],
      ["Battery", "5,000mAh, 18W fast charge (charger included)"],
      ["SIM", "Dual SIM (4G LTE — works with MTN & Airtel)"],
      ["In the box", "Phone, 18W charger, USB-C cable, case, screen protector"],
    ],
  },
  {
    slug: "samsung-galaxy-a16",
    title: "Samsung Galaxy A16 — 128GB, 50MP camera, 5,000mAh",
    brand: "Samsung",
    category: "phones",
    art: "phoneAccent",
    price: 195000,
    stars: "★★★★★",
    count: 487,
    stock: 31,
    sold: 142,
    blurb: [
      "Samsung's best-selling budget phone: a bright Super AMOLED screen, a reliable 50MP camera, and six years of software updates — rare at this price.",
      "Official Samsung Rwanda stock with a 12-month warranty.",
    ],
    highlights: [
      ["Display", '6.7" Super AMOLED, 90Hz'],
      ["Memory", "128GB storage · 4GB RAM"],
      ["Camera", "50MP main + 5MP ultrawide"],
      ["Battery", "5,000mAh · 25W fast charging"],
      ["Warranty", "12 months, official Samsung Rwanda"],
    ],
    specs: [
      ["Display", '6.7" Super AMOLED, 90Hz'],
      ["Processor", "Exynos 1330 / Helio G99"],
      ["Storage / RAM", "128GB / 4GB"],
      ["Rear camera", "50MP + 5MP ultrawide + 2MP macro"],
      ["Battery", "5,000mAh, 25W fast charge"],
      ["SIM", "Dual SIM (4G LTE)"],
      ["In the box", "Phone, USB-C cable (charger sold separately)"],
    ],
  },
  {
    slug: "infinix-hot-40i",
    title: 'Infinix Hot 40i — 6.6", 256GB, 90Hz display',
    brand: "Infinix",
    category: "phones",
    art: "phoneRing",
    price: 135000,
    stars: "★★★★☆",
    count: 176,
    stock: 18,
    sold: 64,
    blurb: [
      "Huge 256GB storage for photos, apps and music, plus a smooth 90Hz display — the Hot 40i is built for everyday life without compromise.",
      "Official stock with a 12-month warranty, charger included.",
    ],
    highlights: [
      ["Display", '6.6" HD+ 90Hz'],
      ["Memory", "256GB storage · 8GB RAM"],
      ["Camera", "50MP AI dual camera"],
      ["Battery", "5,000mAh · 18W charging"],
      ["Warranty", "12 months official"],
    ],
    specs: [
      ["Display", '6.6" HD+ IPS, 90Hz'],
      ["Processor", "Unisoc T606, octa-core"],
      ["Storage / RAM", "256GB / 8GB"],
      ["Rear camera", "50MP AI dual camera"],
      ["Battery", "5,000mAh, 18W fast charge"],
      ["SIM", "Dual SIM (4G LTE)"],
      ["In the box", "Phone, charger, cable, case"],
    ],
  },
  {
    slug: "itel-a70",
    title: 'itel A70 — 6.6" HD+, 128GB, big battery',
    brand: "itel",
    category: "phones",
    art: "phonePlain",
    price: 85000,
    stars: "★★★★☆",
    count: 93,
    stock: 40,
    sold: 118,
    blurb: [
      "The most affordable smartphone in our shop that we still fully stand behind: a big screen, 128GB of storage, and a battery that keeps going.",
      "12-month warranty, charger in the box.",
    ],
    highlights: [
      ["Display", '6.6" HD+'],
      ["Memory", "128GB storage · 4GB RAM"],
      ["Camera", "13MP AI camera"],
      ["Battery", "5,000mAh"],
      ["Warranty", "12 months official"],
    ],
    specs: [
      ["Display", '6.6" HD+ IPS'],
      ["Processor", "Unisoc T603"],
      ["Storage / RAM", "128GB / 4GB"],
      ["Rear camera", "13MP AI camera"],
      ["Battery", "5,000mAh"],
      ["SIM", "Dual SIM (4G LTE)"],
      ["In the box", "Phone, charger, cable"],
    ],
  },
  {
    slug: "xiaomi-redmi-13c",
    title: 'Xiaomi Redmi 13C — 6.74", 128GB, 50MP triple camera',
    brand: "Xiaomi",
    category: "phones",
    art: "phoneSquare",
    price: 155000,
    oldPrice: 168000,
    off: "-8%",
    stars: "★★★★☆",
    count: 261,
    stock: 15,
    sold: 77,
    blurb: [
      "A crowd favourite: big 90Hz screen, capable 50MP triple camera, and Xiaomi's polished MIUI experience.",
      "Official stock, 12-month warranty.",
    ],
    highlights: [
      ["Display", '6.74" HD+ 90Hz'],
      ["Memory", "128GB storage · 6GB RAM"],
      ["Camera", "50MP triple camera"],
      ["Battery", "5,000mAh · 18W charging"],
      ["Warranty", "12 months official"],
    ],
    specs: [
      ["Display", '6.74" HD+ IPS, 90Hz'],
      ["Processor", "MediaTek Helio G85"],
      ["Storage / RAM", "128GB / 6GB"],
      ["Rear camera", "50MP triple camera"],
      ["Battery", "5,000mAh, 18W fast charge"],
      ["SIM", "Dual SIM (4G LTE)"],
      ["In the box", "Phone, charger, cable, case"],
    ],
  },
  {
    slug: "samsung-galaxy-tab-a9",
    title: 'Samsung Galaxy Tab A9 — 8.7", 64GB, WiFi + 4G',
    brand: "Samsung",
    category: "phones",
    art: "tablet",
    price: 265000,
    stars: "★★★★★",
    count: 74,
    stock: 9,
    sold: 22,
    blurb: [
      "A compact tablet for reading, movies, school work and video calls — with a SIM slot so you can use it anywhere with mobile data.",
      "Official Samsung stock, 12-month warranty.",
    ],
    highlights: [
      ["Display", '8.7" WXGA+'],
      ["Memory", "64GB storage · 4GB RAM"],
      ["Connectivity", "WiFi + 4G (SIM slot)"],
      ["Battery", "5,100mAh"],
      ["Warranty", "12 months, official Samsung Rwanda"],
    ],
    specs: [
      ["Display", '8.7" WXGA+ (1340 × 800)'],
      ["Processor", "MediaTek Helio G99"],
      ["Storage / RAM", "64GB / 4GB (microSD up to 1TB)"],
      ["Battery", "5,100mAh"],
      ["Connectivity", "WiFi, Bluetooth 5.3, 4G LTE"],
      ["In the box", "Tablet, cable (charger sold separately)"],
    ],
  },
  {
    slug: "tecno-camon-30",
    title: 'Tecno Camon 30 — 6.78" FHD+, 256GB, 50MP selfie',
    brand: "Tecno",
    category: "phones",
    art: "phoneLines",
    price: 295000,
    stars: "★★★★★",
    count: 147,
    stock: 12,
    sold: 41,
    blurb: [
      "Tecno's camera flagship: a sharp FHD+ AMOLED display and a 50MP selfie camera that makes it the choice for content creators.",
      "Official Tecno Rwanda stock, 12-month warranty.",
    ],
    highlights: [
      ["Display", '6.78" FHD+ AMOLED, 120Hz'],
      ["Memory", "256GB storage · 12GB RAM"],
      ["Camera", "50MP main · 50MP selfie"],
      ["Battery", "5,000mAh · 70W fast charging"],
      ["Warranty", "12 months, official Tecno Rwanda"],
    ],
    specs: [
      ["Display", '6.78" FHD+ AMOLED, 120Hz'],
      ["Processor", "MediaTek Dimensity 7020"],
      ["Storage / RAM", "256GB / 12GB"],
      ["Rear camera", "50MP main + 2MP depth"],
      ["Front camera", "50MP with dual flash"],
      ["Battery", "5,000mAh, 70W fast charge"],
      ["In the box", "Phone, 70W charger, cable, case"],
    ],
  },
  {
    slug: "infinix-note-40",
    title: 'Infinix Note 40 — 6.78" AMOLED, 256GB, 108MP',
    brand: "Infinix",
    category: "phones",
    art: "phoneDots",
    price: 335000,
    stars: "★★★★☆",
    count: 58,
    stock: 7,
    sold: 19,
    blurb: [
      "A big, beautiful AMOLED screen and a 108MP camera — the Note 40 competes with phones twice its price.",
      "Official stock, 12-month warranty, 45W charger included.",
    ],
    highlights: [
      ["Display", '6.78" FHD+ AMOLED, 120Hz'],
      ["Memory", "256GB storage · 8GB RAM"],
      ["Camera", "108MP main camera"],
      ["Battery", "5,000mAh · 45W charging"],
      ["Warranty", "12 months official"],
    ],
    specs: [
      ["Display", '6.78" FHD+ AMOLED, 120Hz'],
      ["Processor", "MediaTek Helio G99 Ultimate"],
      ["Storage / RAM", "256GB / 8GB"],
      ["Rear camera", "108MP main + 2MP macro"],
      ["Battery", "5,000mAh, 45W fast charge"],
      ["In the box", "Phone, 45W charger, cable, case"],
    ],
  },
  {
    slug: "itel-s24",
    title: 'itel S24 — 6.6" 90Hz, 128GB, 50MP camera',
    brand: "itel",
    category: "phones",
    art: "phoneCam",
    price: 108000,
    oldPrice: 120000,
    off: "-10%",
    stars: "★★★★☆",
    count: 41,
    stock: 26,
    sold: 33,
    blurb: [
      "A stylish budget phone with a smooth 90Hz screen and a real 50MP camera.",
      "12-month warranty, charger in the box.",
    ],
    highlights: [
      ["Display", '6.6" HD+ 90Hz'],
      ["Memory", "128GB storage · 4GB RAM"],
      ["Camera", "50MP main camera"],
      ["Battery", "5,000mAh"],
      ["Warranty", "12 months official"],
    ],
    specs: [
      ["Display", '6.6" HD+ IPS, 90Hz'],
      ["Processor", "Unisoc T606"],
      ["Storage / RAM", "128GB / 4GB"],
      ["Rear camera", "50MP main camera"],
      ["Battery", "5,000mAh"],
      ["In the box", "Phone, charger, cable"],
    ],
  },
  {
    slug: "hisense-43-smart-tv",
    title: 'Hisense 43" Smart TV — Full HD, Netflix & YouTube built in',
    brand: "Hisense",
    category: "tv",
    art: "tv",
    price: 320000,
    oldPrice: 365000,
    off: "-12%",
    stars: "★★★★★",
    count: 96,
    stock: 11,
    sold: 37,
    blurb: [
      "A crisp Full HD smart TV with Netflix, YouTube and DStv Now built in — connect it to WiFi and you're watching in minutes.",
      "Official Hisense stock with a 12-month warranty. We can arrange wall mounting in Kigali.",
    ],
    highlights: [
      ["Screen", '43" Full HD (1920 × 1080)'],
      ["Smart", "VIDAA OS — Netflix, YouTube, Prime"],
      ["Connections", "2× HDMI, 2× USB, WiFi"],
      ["Sound", "Dolby Audio"],
      ["Warranty", "12 months, official Hisense"],
    ],
    specs: [
      ["Screen", '43" Full HD LED'],
      ["Smart platform", "VIDAA OS with app store"],
      ["Connections", "2× HDMI, 2× USB, AV, WiFi, Bluetooth"],
      ["Sound", "2× 8W, Dolby Audio"],
      ["Power", "220–240V"],
      ["In the box", "TV, stand, remote, batteries"],
    ],
  },
  {
    slug: "lg-55-uhd-tv",
    title: 'LG 55" UHD 4K Smart TV — webOS, HDR10',
    brand: "LG",
    category: "tv",
    art: "tvPlay",
    price: 585000,
    stars: "★★★★★",
    count: 64,
    stock: 5,
    sold: 14,
    blurb: [
      "Cinema at home: a big 55-inch 4K screen with HDR and LG's easy webOS smart platform.",
      "Official LG stock, 12-month warranty. Delivery and installation available in Kigali.",
    ],
    highlights: [
      ["Screen", '55" 4K UHD (3840 × 2160)'],
      ["Smart", "webOS — Netflix, YouTube, Prime"],
      ["Picture", "HDR10, AI upscaling"],
      ["Connections", "3× HDMI, 2× USB, WiFi"],
      ["Warranty", "12 months, official LG"],
    ],
    specs: [
      ["Screen", '55" 4K UHD LED'],
      ["Smart platform", "webOS"],
      ["Picture", "HDR10 Pro, 4K upscaler"],
      ["Connections", "3× HDMI, 2× USB, WiFi, Bluetooth"],
      ["Sound", "2× 10W"],
      ["In the box", "TV, stand, Magic Remote"],
    ],
  },
  {
    slug: "hp-laptop-15",
    title: "HP Laptop 15 — Intel Core i5, 8GB RAM, 512GB SSD",
    brand: "HP",
    category: "computers",
    art: "laptop",
    price: 720000,
    stars: "★★★★☆",
    count: 129,
    stock: 8,
    sold: 26,
    blurb: [
      "A dependable everyday laptop for work, school and business: fast SSD storage, a full HD screen, and a comfortable full-size keyboard.",
      "Sealed official stock with a 12-month warranty. We install Windows, Office and antivirus for free before delivery.",
    ],
    highlights: [
      ["Processor", "Intel Core i5 (12th gen)"],
      ["Memory", "8GB RAM · 512GB SSD"],
      ["Display", '15.6" Full HD'],
      ["Battery", "Up to 8 hours"],
      ["Warranty", "12 months, official HP"],
    ],
    specs: [
      ["Processor", "Intel Core i5-1235U"],
      ["Memory", "8GB DDR4 (upgradeable)"],
      ["Storage", "512GB NVMe SSD"],
      ["Display", '15.6" Full HD anti-glare'],
      ["Ports", "USB-C, 2× USB-A, HDMI, SD reader"],
      ["OS", "Windows 11 (activated, free setup)"],
      ["In the box", "Laptop, 45W charger"],
    ],
  },
  {
    slug: "jbl-flip-6",
    title: "JBL Flip 6 Portable Bluetooth Speaker — Waterproof",
    brand: "JBL",
    category: "audio",
    art: "speaker",
    price: 125000,
    oldPrice: 148000,
    off: "-15%",
    stars: "★★★★★",
    count: 158,
    stock: 20,
    sold: 55,
    blurb: [
      "Big JBL sound in a speaker you can drop in a bag — fully waterproof, 12 hours of battery, and loud enough for a party.",
      "Genuine JBL with a 12-month warranty.",
    ],
    highlights: [
      ["Sound", "30W output, deep bass"],
      ["Battery", "12 hours playtime"],
      ["Build", "IP67 waterproof & dustproof"],
      ["Connectivity", "Bluetooth 5.1"],
      ["Warranty", "12 months, genuine JBL"],
    ],
    specs: [
      ["Output", "30W RMS"],
      ["Battery", "12 hours, USB-C charging"],
      ["Waterproofing", "IP67"],
      ["Bluetooth", "5.1, PartyBoost pairing"],
      ["In the box", "Speaker, USB-C cable"],
    ],
  },
  {
    slug: "anker-powercore-20000",
    title: "Anker PowerCore 20,000mAh Power Bank — Fast charge",
    brand: "Anker",
    category: "power",
    art: "powerbank",
    price: 35000,
    oldPrice: 44000,
    off: "-20%",
    stars: "★★★★☆",
    count: 342,
    stock: 45,
    sold: 210,
    blurb: [
      "Charge your phone four to five times from one power bank — essential for load shedding, travel and long days.",
      "Genuine Anker with an 18-month warranty.",
    ],
    highlights: [
      ["Capacity", "20,000mAh (4–5 phone charges)"],
      ["Charging", "20W USB-C fast charge"],
      ["Ports", "USB-C + 2× USB-A"],
      ["Safety", "Anker MultiProtect"],
      ["Warranty", "18 months, genuine Anker"],
    ],
    specs: [
      ["Capacity", "20,000mAh / 72Wh"],
      ["Output", "20W USB-C PD, 18W USB-A"],
      ["Input", "USB-C fast recharge"],
      ["Weight", "343g"],
      ["In the box", "Power bank, USB-C cable, pouch"],
    ],
  },
  {
    slug: "oraimo-freepods-4",
    title: "Oraimo FreePods 4 — Wireless earbuds, 35hr battery",
    brand: "Oraimo",
    category: "audio",
    art: "earbuds",
    price: 28000,
    stars: "★★★★☆",
    count: 521,
    stock: 60,
    sold: 340,
    blurb: [
      "Our best-selling earbuds: clear calls, punchy bass, and 35 hours of total battery with the charging case.",
      "Genuine Oraimo with a 12-month warranty.",
    ],
    highlights: [
      ["Battery", "35 hours total with case"],
      ["Sound", "ENC clear calls, bass boost"],
      ["Comfort", "Lightweight, touch controls"],
      ["Connectivity", "Bluetooth 5.3"],
      ["Warranty", "12 months, genuine Oraimo"],
    ],
    specs: [
      ["Battery", "35h total (case), 7h per charge"],
      ["Bluetooth", "5.3, auto pairing"],
      ["Calls", "4-mic ENC noise cancelling"],
      ["Charging", "USB-C"],
      ["In the box", "Earbuds, case, cable, ear tips"],
    ],
  },
  {
    slug: "tp-link-archer-c6",
    title: "TP-Link Archer C6 WiFi Router — Dual band, 4 antennas",
    brand: "TP-Link",
    category: "networking",
    art: "router",
    price: 42000,
    stars: "★★★★☆",
    count: 88,
    stock: 17,
    sold: 48,
    blurb: [
      "Strong, stable WiFi for the whole house — dual band, four antennas, easy setup from your phone. Works with Canal Box, Liquid Home and Starlink.",
      "Genuine TP-Link with a 24-month warranty.",
    ],
    highlights: [
      ["Speed", "AC1200 dual band"],
      ["Coverage", "4 antennas + beamforming"],
      ["Setup", "Tether app, 5 minutes"],
      ["Ports", "4× LAN, 1× WAN gigabit"],
      ["Warranty", "24 months, genuine TP-Link"],
    ],
    specs: [
      ["WiFi", "AC1200 (300 + 867 Mbps)"],
      ["Antennas", "4 external + beamforming"],
      ["Ports", "1× gigabit WAN, 4× gigabit LAN"],
      ["Management", "TP-Link Tether app"],
      ["In the box", "Router, adapter, LAN cable"],
    ],
  },
  {
    slug: "oraimo-watch-5-lite",
    title: 'Oraimo Watch 5 Lite — 2.01" display, health tracking',
    brand: "Oraimo",
    category: "wearables",
    art: "watch",
    price: 55000,
    stars: "★★★★☆",
    count: 203,
    stock: 28,
    sold: 96,
    blurb: [
      "A big, bright smartwatch that tracks your steps, sleep and heart rate — and takes calls from your wrist.",
      "Genuine Oraimo with a 12-month warranty.",
    ],
    highlights: [
      ["Display", '2.01" HD touch screen'],
      ["Health", "Heart rate, sleep, 100+ sports modes"],
      ["Calls", "Bluetooth calling from the wrist"],
      ["Battery", "Up to 10 days"],
      ["Warranty", "12 months, genuine Oraimo"],
    ],
    specs: [
      ["Display", '2.01" HD touch'],
      ["Battery", "Up to 10 days typical use"],
      ["Health", "Heart rate, SpO2, sleep tracking"],
      ["Water resistance", "IP68"],
      ["In the box", "Watch, strap, charging cable"],
    ],
  },
  {
    slug: "dualsense-controller",
    title: "DualSense Wireless Controller — for PS5 & PC",
    brand: "Sony",
    category: "gaming",
    art: "gamepad",
    price: 95000,
    stars: "★★★★★",
    count: 112,
    stock: 10,
    sold: 30,
    blurb: [
      "The official PS5 controller with haptic feedback and adaptive triggers — also works great on PC.",
      "Genuine Sony with a 12-month warranty.",
    ],
    highlights: [
      ["Compatibility", "PS5, PC, mobile"],
      ["Feedback", "Haptics + adaptive triggers"],
      ["Battery", "Built-in rechargeable"],
      ["Connectivity", "Wireless + USB-C"],
      ["Warranty", "12 months, genuine Sony"],
    ],
    specs: [
      ["Compatibility", "PS5, Windows PC, Android, iOS"],
      ["Features", "Haptic feedback, adaptive triggers, mic"],
      ["Battery", "Rechargeable, USB-C"],
      ["In the box", "Controller, USB-C cable"],
    ],
  },
];

export function findProduct(slug) {
  return products.find(function (p) {
    return p.slug === slug;
  });
}

export function byCategory(category) {
  return products.filter(function (p) {
    return p.category === category;
  });
}

export function bySlugs(slugs) {
  return slugs.map(findProduct).filter(Boolean);
}
