// All shop products live here for now.
// Later this will move to a real database — for the prototype it's one file,
// so adding or editing a product means editing this list only.

export function formatRWF(amount) {
  return "RWF " + amount.toLocaleString("en-US");
}

// Product photos live in /public/products/<slug>.<ext> (jpg unless noted here).
const IMAGE_EXT = {
  "hp-pavilion-15": "png",
};

export function productImage(product) {
  return "/products/" + product.slug + "." + (IMAGE_EXT[product.slug] || "jpg");
}

export const CATEGORIES = {
  phones: "Phones & Tablets",
  computers: "Computers & Laptops",
  audio: "Audio & Sound",
  power: "Power & Accessories",
};

export const products = [
  {
    slug: "samsung-galaxy-a16",
    title: "Samsung Galaxy A16 — 50MP camera, 5,000mAh",
    brand: "Samsung",
    category: "phones",
    art: "phoneAccent",
    price: 195000,
    colors: ["Black", "Light Green", "Blue"],
    stars: "★★★★★",
    count: 487,
    stock: 31,
    sold: 142,
    blurb: [
      "Samsung's best-selling budget phone: a bright Super AMOLED screen, a reliable 50MP camera, and six years of software updates — rare at this price.",
      "Official Samsung Rwanda stock with a 12-month warranty.",
    ],
    highlights: [
      ["Display", '6.7" Super AMOLED, 90Hz'],
      ["Memory", "128GB storage · 4GB RAM"],
      ["Camera", "50MP main + 5MP ultrawide"],
      ["Battery", "5,000mAh · 25W fast charging"],
      ["Warranty", "12 months, official Samsung Rwanda"],
    ],
    specs: [
      ["Display", '6.7" Super AMOLED, 90Hz'],
      ["Processor", "Exynos 1330 / Helio G99"],
      ["Storage / RAM", "128GB / 4GB"],
      ["Rear camera", "50MP + 5MP ultrawide + 2MP macro"],
      ["Battery", "5,000mAh, 25W fast charge"],
      ["SIM", "Dual SIM (4G LTE)"],
      ["In the box", "Phone, USB-C cable (charger sold separately)"],
    ],
  },
  {
    slug: "samsung-galaxy-s25",
    title: "Samsung Galaxy S25 — Snapdragon 8 Elite",
    brand: "Samsung",
    category: "phones",
    price: 1350000,
    colors: ["Navy", "Icy Blue", "Mint", "Silver"],
    storages: [{ label: "256GB", price: 1350000 }, { label: "512GB", price: 1480000 }],
    stars: "★★★★★",
    count: 38,
    stock: 6,
    sold: 14,
    blurb: [
      "Samsung's compact flagship: Snapdragon 8 Elite speed, a bright 120Hz AMOLED display, and Galaxy AI built in — the Android answer to the iPhone Pro.",
      "Official Samsung stock, sealed, with a 12-month warranty from MPS.",
    ],
    highlights: [
      ["Display", '6.2" Dynamic AMOLED 2X, 120Hz'],
      ["Chip", "Snapdragon 8 Elite"],
      ["Memory", "256GB storage · 12GB RAM"],
      ["Camera", "50MP triple with 3x telephoto"],
      ["Warranty", "12 months, official Samsung"],
    ],
    specs: [
      ["Display", '6.2" Dynamic AMOLED 2X, 120Hz, 2600 nits'],
      ["Chip", "Snapdragon 8 Elite for Galaxy"],
      ["Storage / RAM", "256GB / 12GB"],
      ["Rear camera", "50MP main + 12MP ultrawide + 10MP 3x telephoto"],
      ["Front camera", "12MP"],
      ["Battery", "4,000mAh, 25W fast charge"],
      ["SIM", "Dual SIM + eSIM (works with MTN & Airtel)"],
      ["In the box", "Phone, USB-C cable"],
    ],
  },
  {
    slug: "samsung-galaxy-a56",
    title: 'Samsung Galaxy A56 — 6.7" 120Hz AMOLED',
    brand: "Samsung",
    category: "phones",
    price: 445000,
    colors: ["Graphite", "Olive", "Light Gray", "Pink"],
    storages: [{ label: "128GB", price: 445000 }, { label: "256GB", price: 495000 }],
    stars: "★★★★★",
    count: 52,
    stock: 10,
    sold: 19,
    blurb: [
      "The mid-range king: a big 120Hz Super AMOLED screen, 45W fast charging, and six years of updates — flagship feel without the flagship price.",
      "Official Samsung stock with a 12-month warranty.",
    ],
    highlights: [
      ["Display", '6.7" Super AMOLED, 120Hz'],
      ["Chip", "Exynos 1580"],
      ["Memory", "256GB storage · 8GB RAM"],
      ["Camera", "50MP triple camera"],
      ["Warranty", "12 months, official Samsung"],
    ],
    specs: [
      ["Display", '6.7" Super AMOLED, 120Hz'],
      ["Chip", "Exynos 1580"],
      ["Storage / RAM", "256GB / 8GB"],
      ["Rear camera", "50MP main + 12MP ultrawide + 5MP macro"],
      ["Battery", "5,000mAh, 45W fast charge"],
      ["SIM", "Dual SIM (works with MTN & Airtel)"],
      ["In the box", "Phone, USB-C cable"],
    ],
  },
  {
    slug: "infinix-hot-40i",
    title: 'Infinix Hot 40i — 6.6", 90Hz display',
    brand: "Infinix",
    category: "phones",
    art: "phoneRing",
    price: 135000,
    colors: ["Palm Blue", "Starlit Black", "Horizon Gold"],
    oldPrice: 145000,
    off: "-7%",
    stars: "★★★★☆",
    count: 176,
    stock: 18,
    sold: 64,
    blurb: [
      "Huge 256GB storage for photos, apps and music, plus a smooth 90Hz display — the Hot 40i is built for everyday life without compromise.",
      "Official stock with a 12-month warranty, charger included.",
    ],
    highlights: [
      ["Display", '6.6" HD+ 90Hz'],
      ["Memory", "256GB storage · 8GB RAM"],
      ["Camera", "50MP AI dual camera"],
      ["Battery", "5,000mAh · 18W charging"],
      ["Warranty", "12 months official"],
    ],
    specs: [
      ["Display", '6.6" HD+ IPS, 90Hz'],
      ["Processor", "Unisoc T606, octa-core"],
      ["Storage / RAM", "256GB / 8GB"],
      ["Rear camera", "50MP AI dual camera"],
      ["Battery", "5,000mAh, 18W fast charge"],
      ["SIM", "Dual SIM (4G LTE)"],
      ["In the box", "Phone, charger, cable, case"],
    ],
  },
  {
    slug: "itel-a70",
    title: 'itel A70 — 6.6" HD+, big battery',
    brand: "itel",
    category: "phones",
    art: "phonePlain",
    price: 85000,
    colors: ["Azure Blue", "Brilliant Black", "Field Green"],
    stars: "★★★★☆",
    count: 93,
    stock: 40,
    sold: 118,
    blurb: [
      "The most affordable smartphone in our shop that we still fully stand behind: a big screen, 128GB of storage, and a battery that keeps going.",
      "12-month warranty, charger in the box.",
    ],
    highlights: [
      ["Display", '6.6" HD+'],
      ["Memory", "128GB storage · 4GB RAM"],
      ["Camera", "13MP AI camera"],
      ["Battery", "5,000mAh"],
      ["Warranty", "12 months official"],
    ],
    specs: [
      ["Display", '6.6" HD+ IPS'],
      ["Processor", "Unisoc T603"],
      ["Storage / RAM", "128GB / 4GB"],
      ["Rear camera", "13MP AI camera"],
      ["Battery", "5,000mAh"],
      ["SIM", "Dual SIM (4G LTE)"],
      ["In the box", "Phone, charger, cable"],
    ],
  },
  {
    slug: "iphone-17-pro-max",
    title: "Apple iPhone 17 Pro Max — A19 Pro, 8x zoom",
    brand: "Apple",
    category: "phones",
    price: 2590000,
    colors: ["Cosmic Orange", "Deep Blue", "Silver"],
    storages: [{ label: "256GB", price: 2590000 }, { label: "512GB", price: 2890000 }],
    stars: "★★★★★",
    count: 12,
    stock: 4,
    sold: 6,
    blurb: [
      "The newest iPhone, in the color everyone is talking about: Cosmic Orange. A19 Pro chip, a 6.9-inch ProMotion display, and the new 48MP Pro Fusion camera system with 8x optical-quality zoom.",
      "Brand new, sealed in the box, with a 12-month warranty from MPS. Installment plan available — take it home with a 40–50% deposit.",
    ],
    highlights: [
      ["Display", '6.9" LTPO Super Retina XDR, 120Hz ProMotion'],
      ["Chip", "Apple A19 Pro"],
      ["Storage", "256GB"],
      ["Camera", "48MP Pro Fusion triple, 8x optical-quality zoom"],
      ["Color", "Cosmic Orange"],
      ["Warranty", "12 months, MPS Kigali"],
    ],
    specs: [
      ["Display", '6.9" LTPO Super Retina XDR OLED, 120Hz ProMotion'],
      ["Chip", "Apple A19 Pro"],
      ["Storage / RAM", "256GB / 12GB"],
      ["Rear camera", "48MP main + 48MP ultrawide + 48MP telephoto (8x optical-quality)"],
      ["Front camera", "18MP Center Stage"],
      ["Battery", "Up to 37h video, USB-C + MagSafe"],
      ["SIM", "eSIM + nano-SIM (works with MTN & Airtel)"],
      ["In the box", "iPhone, USB-C cable"],
    ],
  },
  {
    slug: "iphone-xr",
    title: "Apple iPhone XR — Liquid Retina display",
    brand: "Apple",
    category: "phones",
    price: 295000,
    oldPrice: 320000,
    colors: ["Black", "White", "Blue", "Coral", "Yellow", "Red"],
    storages: [{ label: "64GB", price: 295000 }, { label: "128GB", price: 335000 }],
    off: "-8%",
    stars: "★★★★☆",
    count: 268,
    stock: 17,
    sold: 121,
    blurb: [
      "The cheapest way to own an iPhone: Face ID, a big Liquid Retina display, and a camera that still beats many new budget phones.",
      "Comes boxed with a 12-month warranty from MPS — available in several colors, ask us on WhatsApp.",
    ],
    highlights: [
      ["Display", '6.1" Liquid Retina LCD'],
      ["Chip", "Apple A12 Bionic"],
      ["Storage", "64GB"],
      ["Camera", "12MP wide, Smart HDR"],
      ["Warranty", "12 months, MPS Kigali"],
    ],
    specs: [
      ["Display", '6.1" Liquid Retina LCD, 828 × 1792'],
      ["Chip", "Apple A12 Bionic"],
      ["Storage / RAM", "64GB / 3GB"],
      ["Rear camera", "12MP wide, Smart HDR"],
      ["Front camera", "7MP TrueDepth, Face ID"],
      ["Battery", "Up to 16h video, wireless charging"],
      ["SIM", "Nano-SIM (works with MTN & Airtel)"],
      ["In the box", "iPhone, Lightning cable"],
    ],
  },
  {
    slug: "iphone-11",
    title: "Apple iPhone 11 — dual 12MP camera",
    brand: "Apple",
    category: "phones",
    price: 395000,
    colors: ["Black", "White", "Purple", "Green", "Red"],
    storages: [{ label: "64GB", price: 395000 }, { label: "128GB", price: 435000 }],
    stars: "★★★★★",
    count: 197,
    stock: 13,
    sold: 88,
    blurb: [
      "One of the most loved iPhones in Rwanda: the dual camera with Night mode, all-day battery, and that unmistakable iPhone feel — at a friendly price.",
      "Comes boxed with a 12-month warranty from MPS.",
    ],
    highlights: [
      ["Display", '6.1" Liquid Retina LCD'],
      ["Chip", "Apple A13 Bionic"],
      ["Storage", "64GB"],
      ["Camera", "12MP dual with Night mode"],
      ["Warranty", "12 months, MPS Kigali"],
    ],
    specs: [
      ["Display", '6.1" Liquid Retina LCD, 828 × 1792'],
      ["Chip", "Apple A13 Bionic"],
      ["Storage / RAM", "64GB / 4GB"],
      ["Rear camera", "12MP wide + 12MP ultrawide, Night mode"],
      ["Front camera", "12MP TrueDepth, Face ID"],
      ["Battery", "Up to 17h video, wireless charging"],
      ["SIM", "Nano-SIM (works with MTN & Airtel)"],
      ["In the box", "iPhone, Lightning cable"],
    ],
  },
  {
    slug: "iphone-12",
    title: "Apple iPhone 12 — Super Retina XDR OLED",
    brand: "Apple",
    category: "phones",
    price: 520000,
    colors: ["Black", "White", "Blue", "Green", "Purple", "Red"],
    storages: [{ label: "64GB", price: 520000 }, { label: "128GB", price: 560000 }],
    stars: "★★★★☆",
    count: 158,
    stock: 14,
    sold: 45,
    blurb: [
      "The most affordable way into the Apple world: the iPhone 12 still feels fast, takes excellent photos, and gets the latest iOS updates.",
      "Brand new, sealed in the box, with a 12-month warranty from MPS.",
    ],
    highlights: [
      ["Display", '6.1" Super Retina XDR OLED'],
      ["Chip", "Apple A14 Bionic"],
      ["Storage", "64GB"],
      ["Camera", "12MP dual (wide + ultrawide)"],
      ["Warranty", "12 months, MPS Kigali"],
    ],
    specs: [
      ["Display", '6.1" Super Retina XDR OLED, 1170 × 2532'],
      ["Chip", "Apple A14 Bionic"],
      ["Storage", "64GB"],
      ["Rear camera", "12MP wide + 12MP ultrawide"],
      ["Front camera", "12MP TrueDepth, Face ID"],
      ["Battery", "Wireless & MagSafe charging"],
      ["SIM", "Nano-SIM + eSIM (works with MTN & Airtel)"],
      ["In the box", "iPhone, USB-C to Lightning cable"],
    ],
  },
  {
    slug: "iphone-13",
    title: "Apple iPhone 13 — A15 Bionic, dual 12MP",
    brand: "Apple",
    category: "phones",
    price: 748000,
    colors: ["Midnight", "Starlight", "Blue", "Pink", "Green"],
    storages: [{ label: "128GB", price: 748000 }, { label: "256GB", price: 828000 }],
    stars: "★★★★★",
    count: 342,
    stock: 21,
    sold: 96,
    blurb: [
      "Our best-selling iPhone: great camera, all-day battery, and years of iOS updates ahead of it — the sweet spot between price and performance.",
      "Brand new, sealed in the box, with a 12-month warranty from MPS.",
    ],
    highlights: [
      ["Display", '6.1" Super Retina XDR OLED'],
      ["Chip", "Apple A15 Bionic"],
      ["Storage", "128GB"],
      ["Camera", "12MP dual with Cinematic mode"],
      ["Warranty", "12 months, MPS Kigali"],
    ],
    specs: [
      ["Display", '6.1" Super Retina XDR OLED, 1170 × 2532'],
      ["Chip", "Apple A15 Bionic"],
      ["Storage", "128GB"],
      ["Rear camera", "12MP wide + 12MP ultrawide, Cinematic mode"],
      ["Front camera", "12MP TrueDepth, Face ID"],
      ["Battery", "Up to 19h video, MagSafe"],
      ["SIM", "Nano-SIM + eSIM (works with MTN & Airtel)"],
      ["In the box", "iPhone, USB-C to Lightning cable"],
    ],
  },
  {
    slug: "iphone-14",
    title: "Apple iPhone 14 — Photonic Engine camera",
    brand: "Apple",
    category: "phones",
    price: 895000,
    colors: ["Midnight", "Starlight", "Blue", "Purple", "Yellow"],
    storages: [{ label: "128GB", price: 895000 }, { label: "256GB", price: 975000 }],
    stars: "★★★★★",
    count: 187,
    stock: 16,
    sold: 58,
    blurb: [
      "A refined iPhone 13 with a better camera in low light, longer battery life, and Crash Detection.",
      "Brand new, sealed in the box, with a 12-month warranty from MPS.",
    ],
    highlights: [
      ["Display", '6.1" Super Retina XDR OLED'],
      ["Chip", "Apple A15 Bionic (5-core GPU)"],
      ["Storage", "128GB"],
      ["Camera", "12MP dual, Photonic Engine"],
      ["Warranty", "12 months, MPS Kigali"],
    ],
    specs: [
      ["Display", '6.1" Super Retina XDR OLED, 1170 × 2532'],
      ["Chip", "Apple A15 Bionic, 5-core GPU"],
      ["Storage", "128GB"],
      ["Rear camera", "12MP wide + 12MP ultrawide, Photonic Engine"],
      ["Front camera", "12MP with autofocus, Face ID"],
      ["Battery", "Up to 20h video, MagSafe"],
      ["SIM", "Nano-SIM + eSIM (works with MTN & Airtel)"],
      ["In the box", "iPhone, USB-C to Lightning cable"],
    ],
  },
  {
    slug: "iphone-15",
    title: "Apple iPhone 15 — 48MP camera, USB-C",
    brand: "Apple",
    category: "phones",
    price: 1150000,
    colors: ["Black", "Blue", "Pink", "Yellow", "Green"],
    storages: [{ label: "128GB", price: 1150000 }, { label: "256GB", price: 1250000 }],
    stars: "★★★★★",
    count: 226,
    stock: 12,
    sold: 63,
    blurb: [
      "The iPhone 15 brings the 48MP camera, Dynamic Island and USB-C — one cable for your phone, laptop and accessories.",
      "Brand new, sealed in the box, with a 12-month warranty from MPS.",
    ],
    highlights: [
      ["Display", '6.1" Super Retina XDR, Dynamic Island'],
      ["Chip", "Apple A16 Bionic"],
      ["Storage", "128GB"],
      ["Camera", "48MP main + 12MP ultrawide"],
      ["Warranty", "12 months, MPS Kigali"],
    ],
    specs: [
      ["Display", '6.1" Super Retina XDR OLED, Dynamic Island'],
      ["Chip", "Apple A16 Bionic"],
      ["Storage", "128GB"],
      ["Rear camera", "48MP main + 12MP ultrawide, 2x optical-quality zoom"],
      ["Front camera", "12MP with autofocus, Face ID"],
      ["Battery", "Up to 20h video, USB-C + MagSafe"],
      ["SIM", "Nano-SIM + eSIM (works with MTN & Airtel)"],
      ["In the box", "iPhone, USB-C cable"],
    ],
  },
  {
    slug: "iphone-15-pro",
    title: "Apple iPhone 15 Pro — titanium, A17 Pro",
    brand: "Apple",
    category: "phones",
    price: 1580000,
    colors: ["Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"],
    storages: [{ label: "128GB", price: 1580000 }, { label: "256GB", price: 1700000 }],
    stars: "★★★★★",
    count: 84,
    stock: 7,
    sold: 21,
    blurb: [
      "The Pro experience: titanium body, 120Hz ProMotion display, the A17 Pro chip, and a 3x telephoto camera — everything the standard iPhone 15 has, and more.",
      "Brand new, sealed in the box, with a 12-month warranty from MPS. Installment plan available.",
    ],
    highlights: [
      ["Display", '6.1" LTPO Super Retina XDR, 120Hz ProMotion'],
      ["Chip", "Apple A17 Pro"],
      ["Storage", "128GB"],
      ["Camera", "48MP main + 3x telephoto"],
      ["Warranty", "12 months, MPS Kigali"],
    ],
    specs: [
      ["Display", '6.1" LTPO Super Retina XDR OLED, 120Hz ProMotion'],
      ["Chip", "Apple A17 Pro"],
      ["Storage / RAM", "128GB / 8GB"],
      ["Rear camera", "48MP main + 12MP ultrawide + 12MP 3x telephoto"],
      ["Front camera", "12MP with autofocus, Face ID"],
      ["Body", "Titanium, Action button"],
      ["Battery", "Up to 23h video, USB-C + MagSafe"],
      ["SIM", "Nano-SIM + eSIM (works with MTN & Airtel)"],
      ["In the box", "iPhone, USB-C cable"],
    ],
  },
  {
    slug: "iphone-16",
    title: "Apple iPhone 16 — A18, Camera Control",
    brand: "Apple",
    category: "phones",
    price: 1420000,
    colors: ["Black", "White", "Ultramarine", "Teal", "Pink"],
    storages: [{ label: "128GB", price: 1420000 }, { label: "256GB", price: 1520000 }],
    stars: "★★★★★",
    count: 94,
    stock: 9,
    sold: 27,
    blurb: [
      "The latest standard iPhone: A18 chip, 48MP Fusion camera with the new Camera Control button, and Apple Intelligence built in.",
      "Brand new, sealed in the box, with a 12-month warranty from MPS.",
    ],
    highlights: [
      ["Display", '6.1" Super Retina XDR, Dynamic Island'],
      ["Chip", "Apple A18"],
      ["Storage", "128GB"],
      ["Camera", "48MP Fusion + 12MP ultrawide"],
      ["Warranty", "12 months, MPS Kigali"],
    ],
    specs: [
      ["Display", '6.1" Super Retina XDR OLED, Dynamic Island'],
      ["Chip", "Apple A18"],
      ["Storage", "128GB"],
      ["Rear camera", "48MP Fusion + 12MP ultrawide, Camera Control"],
      ["Front camera", "12MP with autofocus, Face ID"],
      ["Battery", "Up to 22h video, USB-C + MagSafe"],
      ["SIM", "Nano-SIM + eSIM (works with MTN & Airtel)"],
      ["In the box", "iPhone, USB-C cable"],
    ],
  },
  {
    slug: "iphone-16-pro-max",
    title: "Apple iPhone 16 Pro Max — titanium, 5x zoom",
    brand: "Apple",
    category: "phones",
    price: 2180000,
    colors: ["Desert Titanium", "Natural Titanium", "White Titanium", "Black Titanium"],
    storages: [{ label: "256GB", price: 2180000 }, { label: "512GB", price: 2420000 }],
    stars: "★★★★★",
    count: 61,
    stock: 6,
    sold: 15,
    blurb: [
      "The biggest and most capable iPhone: 6.9-inch 120Hz display, titanium body, A18 Pro, and a pro camera system with 5x telephoto zoom.",
      "Brand new, sealed in the box, with a 12-month warranty from MPS.",
    ],
    highlights: [
      ["Display", '6.9" LTPO OLED, 120Hz ProMotion'],
      ["Chip", "Apple A18 Pro"],
      ["Storage", "256GB"],
      ["Camera", "48MP triple, 5x telephoto"],
      ["Warranty", "12 months, MPS Kigali"],
    ],
    specs: [
      ["Display", '6.9" LTPO Super Retina XDR OLED, 120Hz'],
      ["Chip", "Apple A18 Pro"],
      ["Storage", "256GB"],
      ["Rear camera", "48MP main + 48MP ultrawide + 12MP 5x telephoto"],
      ["Front camera", "12MP with autofocus, Face ID"],
      ["Battery", "Up to 33h video, USB-C + MagSafe"],
      ["SIM", "Nano-SIM + eSIM (works with MTN & Airtel)"],
      ["In the box", "iPhone, USB-C cable"],
    ],
  },
  {
    slug: "samsung-galaxy-tab-a9",
    title: 'Samsung Galaxy Tab A9 — 8.7", WiFi + 4G',
    brand: "Samsung",
    category: "phones",
    art: "tablet",
    price: 265000,
    colors: ["Graphite", "Silver", "Navy"],
    stars: "★★★★★",
    count: 74,
    stock: 9,
    sold: 22,
    blurb: [
      "A compact tablet for reading, movies, school work and video calls — with a SIM slot so you can use it anywhere with mobile data.",
      "Official Samsung stock, 12-month warranty.",
    ],
    highlights: [
      ["Display", '8.7" WXGA+'],
      ["Memory", "64GB storage · 4GB RAM"],
      ["Connectivity", "WiFi + 4G (SIM slot)"],
      ["Battery", "5,100mAh"],
      ["Warranty", "12 months, official Samsung Rwanda"],
    ],
    specs: [
      ["Display", '8.7" WXGA+ (1340 × 800)'],
      ["Processor", "MediaTek Helio G99"],
      ["Storage / RAM", "64GB / 4GB (microSD up to 1TB)"],
      ["Battery", "5,100mAh"],
      ["Connectivity", "WiFi, Bluetooth 5.3, 4G LTE"],
      ["In the box", "Tablet, cable (charger sold separately)"],
    ],
  },
  {
    slug: "tecno-camon-30",
    title: 'Tecno Camon 30 — 6.78" FHD+, 50MP selfie',
    brand: "Tecno",
    category: "phones",
    art: "phoneLines",
    price: 295000,
    colors: ["Basaltic Dark", "Uyuni Salt White"],
    stars: "★★★★★",
    count: 147,
    stock: 12,
    sold: 41,
    blurb: [
      "Tecno's camera flagship: a sharp FHD+ AMOLED display and a 50MP selfie camera that makes it the choice for content creators.",
      "Official Tecno Rwanda stock, 12-month warranty.",
    ],
    highlights: [
      ["Display", '6.78" FHD+ AMOLED, 120Hz'],
      ["Memory", "256GB storage · 12GB RAM"],
      ["Camera", "50MP main · 50MP selfie"],
      ["Battery", "5,000mAh · 70W fast charging"],
      ["Warranty", "12 months, official Tecno Rwanda"],
    ],
    specs: [
      ["Display", '6.78" FHD+ AMOLED, 120Hz'],
      ["Processor", "MediaTek Dimensity 7020"],
      ["Storage / RAM", "256GB / 12GB"],
      ["Rear camera", "50MP main + 2MP depth"],
      ["Front camera", "50MP with dual flash"],
      ["Battery", "5,000mAh, 70W fast charge"],
      ["In the box", "Phone, 70W charger, cable, case"],
    ],
  },
  {
    slug: "tecno-camon-40",
    title: 'Tecno Camon 40 — 6.78" AMOLED 120Hz',
    brand: "Tecno",
    category: "phones",
    price: 340000,
    colors: ["Galaxy Black", "Emerald Green"],
    stars: "★★★★★",
    count: 63,
    stock: 12,
    sold: 26,
    blurb: [
      "The newest Camon: a sharp 120Hz AMOLED display, a 50MP camera with a one-tap FlashSnap button, and slim design — the content creator's favourite.",
      "Official Tecno Rwanda stock, 12-month warranty.",
    ],
    highlights: [
      ["Display", '6.78" FHD+ AMOLED, 120Hz'],
      ["Chip", "MediaTek Helio G100 Ultimate"],
      ["Memory", "256GB storage · 8GB RAM"],
      ["Camera", "50MP main · 32MP selfie"],
      ["Warranty", "12 months, official Tecno Rwanda"],
    ],
    specs: [
      ["Display", '6.78" FHD+ AMOLED, 120Hz'],
      ["Chip", "MediaTek Helio G100 Ultimate"],
      ["Storage / RAM", "256GB / 8GB"],
      ["Rear camera", "50MP main, FlashSnap button"],
      ["Front camera", "32MP"],
      ["Battery", "5,200mAh, 45W fast charge"],
      ["SIM", "Dual SIM (works with MTN & Airtel)"],
      ["In the box", "Phone, 45W charger, cable, case"],
    ],
  },
  {
    slug: "infinix-note-40",
    title: 'Infinix Note 40 — 6.78" AMOLED, 108MP',
    brand: "Infinix",
    category: "phones",
    art: "phoneDots",
    price: 335000,
    colors: ["Obsidian Black", "Titan Gold"],
    stars: "★★★★☆",
    count: 58,
    stock: 7,
    sold: 19,
    blurb: [
      "A big, beautiful AMOLED screen and a 108MP camera — the Note 40 competes with phones twice its price.",
      "Official stock, 12-month warranty, 45W charger included.",
    ],
    highlights: [
      ["Display", '6.78" FHD+ AMOLED, 120Hz'],
      ["Memory", "256GB storage · 8GB RAM"],
      ["Camera", "108MP main camera"],
      ["Battery", "5,000mAh · 45W charging"],
      ["Warranty", "12 months official"],
    ],
    specs: [
      ["Display", '6.78" FHD+ AMOLED, 120Hz'],
      ["Processor", "MediaTek Helio G99 Ultimate"],
      ["Storage / RAM", "256GB / 8GB"],
      ["Rear camera", "108MP main + 2MP macro"],
      ["Battery", "5,000mAh, 45W fast charge"],
      ["In the box", "Phone, 45W charger, cable, case"],
    ],
  },
  {
    slug: "infinix-note-50",
    title: 'Infinix Note 50 — 6.78" AMOLED 144Hz',
    brand: "Infinix",
    category: "phones",
    price: 380000,
    colors: ["Titanium Grey", "Racing Black"],
    stars: "★★★★☆",
    count: 41,
    stock: 9,
    sold: 17,
    blurb: [
      "Infinix's big-screen powerhouse: a super-smooth 144Hz AMOLED display, 90W fast charging that fills the battery in half an hour, and a metal frame.",
      "Official stock with a 12-month warranty, 90W charger included.",
    ],
    highlights: [
      ["Display", '6.78" FHD+ AMOLED, 144Hz'],
      ["Chip", "MediaTek Helio G100 Ultimate"],
      ["Memory", "256GB storage · 8GB RAM"],
      ["Camera", "64MP main camera"],
      ["Warranty", "12 months official"],
    ],
    specs: [
      ["Display", '6.78" FHD+ AMOLED, 144Hz'],
      ["Chip", "MediaTek Helio G100 Ultimate"],
      ["Storage / RAM", "256GB / 8GB"],
      ["Rear camera", "64MP main + 2MP depth"],
      ["Battery", "5,500mAh, 90W fast charge"],
      ["SIM", "Dual SIM (works with MTN & Airtel)"],
      ["In the box", "Phone, 90W charger, cable, case"],
    ],
  },
  {
    slug: "itel-s24",
    title: 'itel S24 — 6.6" 90Hz, 50MP camera',
    brand: "itel",
    category: "phones",
    art: "phoneCam",
    price: 108000,
    colors: ["Starry Black", "Dawn White"],
    oldPrice: 120000,
    off: "-10%",
    stars: "★★★★☆",
    count: 41,
    stock: 26,
    sold: 33,
    blurb: [
      "A stylish budget phone with a smooth 90Hz screen and a real 50MP camera.",
      "12-month warranty, charger in the box.",
    ],
    highlights: [
      ["Display", '6.6" HD+ 90Hz'],
      ["Memory", "128GB storage · 4GB RAM"],
      ["Camera", "50MP main camera"],
      ["Battery", "5,000mAh"],
      ["Warranty", "12 months official"],
    ],
    specs: [
      ["Display", '6.6" HD+ IPS, 90Hz'],
      ["Processor", "Unisoc T606"],
      ["Storage / RAM", "128GB / 4GB"],
      ["Rear camera", "50MP main camera"],
      ["Battery", "5,000mAh"],
      ["In the box", "Phone, charger, cable"],
    ],
  },
  {
    slug: "hp-laptop-15",
    title: "HP Laptop 15 — Intel Core i5, 8GB RAM, 512GB SSD",
    brand: "HP",
    category: "computers",
    art: "laptop",
    price: 720000,
    stars: "★★★★☆",
    count: 129,
    stock: 8,
    sold: 26,
    blurb: [
      "A dependable everyday laptop for work, school and business: fast SSD storage, a full HD screen, and a comfortable full-size keyboard.",
      "Sealed official stock with a 12-month warranty. We install Windows, Office and antivirus for free before delivery.",
    ],
    highlights: [
      ["Processor", "Intel Core i5 (12th gen)"],
      ["Memory", "8GB RAM · 512GB SSD"],
      ["Display", '15.6" Full HD'],
      ["Battery", "Up to 8 hours"],
      ["Warranty", "12 months, official HP"],
    ],
    specs: [
      ["Processor", "Intel Core i5-1235U"],
      ["Memory", "8GB DDR4 (upgradeable)"],
      ["Storage", "512GB NVMe SSD"],
      ["Display", '15.6" Full HD anti-glare'],
      ["Ports", "USB-C, 2× USB-A, HDMI, SD reader"],
      ["OS", "Windows 11 (activated, free setup)"],
      ["In the box", "Laptop, 45W charger"],
    ],
  },
  {
    slug: "hp-pavilion-15",
    title: "HP Pavilion 15 — Intel Core i7, 16GB RAM, 512GB SSD",
    brand: "HP",
    category: "computers",
    price: 1180000,
    stars: "★★★★☆",
    count: 47,
    stock: 5,
    sold: 11,
    blurb: [
      "A step up for business and creators: 12th-gen Core i7 power, 16GB of RAM for heavy multitasking, and a bright FHD screen with slim bezels — in a light silver body.",
      "Sealed official stock with a 12-month warranty. We install Windows, Office and antivirus for free before delivery.",
    ],
    highlights: [
      ["Processor", "Intel Core i7 (12th gen)"],
      ["Memory", "16GB RAM · 512GB SSD"],
      ["Display", '15.6" Full HD IPS'],
      ["Audio", "B&O tuned speakers"],
      ["Warranty", "12 months, official HP"],
    ],
    specs: [
      ["Processor", "Intel Core i7-1255U, 10 cores"],
      ["Memory", "16GB DDR4"],
      ["Storage", "512GB NVMe SSD"],
      ["Display", '15.6" Full HD IPS, slim bezels'],
      ["Keyboard", "Backlit, full-size with numpad"],
      ["Ports", "USB-C, 2× USB-A, HDMI, SD reader"],
      ["OS", "Windows 11 (activated, free setup)"],
      ["In the box", "Laptop, 65W charger"],
    ],
  },
  {
    slug: "jbl-flip-6",
    title: "JBL Flip 6 Portable Bluetooth Speaker — Waterproof",
    brand: "JBL",
    category: "audio",
    art: "speaker",
    price: 125000,
    oldPrice: 148000,
    off: "-15%",
    stars: "★★★★★",
    count: 158,
    stock: 20,
    sold: 55,
    blurb: [
      "Big JBL sound in a speaker you can drop in a bag — fully waterproof, 12 hours of battery, and loud enough for a party.",
      "Genuine JBL with a 12-month warranty.",
    ],
    highlights: [
      ["Sound", "30W output, deep bass"],
      ["Battery", "12 hours playtime"],
      ["Build", "IP67 waterproof & dustproof"],
      ["Connectivity", "Bluetooth 5.1"],
      ["Warranty", "12 months, genuine JBL"],
    ],
    specs: [
      ["Output", "30W RMS"],
      ["Battery", "12 hours, USB-C charging"],
      ["Waterproofing", "IP67"],
      ["Bluetooth", "5.1, PartyBoost pairing"],
      ["In the box", "Speaker, USB-C cable"],
    ],
  },
  {
    slug: "jbl-go-4",
    title: "JBL Go 4 — Pocket Bluetooth speaker, IP67",
    brand: "JBL",
    category: "audio",
    price: 45000,
    stars: "★★★★☆",
    count: 88,
    stock: 25,
    sold: 61,
    blurb: [
      "Big JBL sound in your pocket: waterproof, dustproof, 7 hours of battery, and a loop to clip it on your bag.",
      "Genuine JBL with a 12-month warranty.",
    ],
    highlights: [
      ["Sound", "JBL Pro Sound, punchy bass"],
      ["Battery", "7 hours playtime"],
      ["Build", "IP67 waterproof & dustproof"],
      ["Connectivity", "Bluetooth 5.3, Auracast"],
      ["Warranty", "12 months, genuine JBL"],
    ],
    specs: [
      ["Output", "4.2W RMS"],
      ["Battery", "7 hours, USB-C charging"],
      ["Waterproofing", "IP67"],
      ["Bluetooth", "5.3 with Auracast"],
      ["In the box", "Speaker, USB-C cable"],
    ],
  },
  {
    slug: "anker-powercore-20000",
    title: "Anker PowerCore 20,000mAh Power Bank — Fast charge",
    brand: "Anker",
    category: "power",
    art: "powerbank",
    price: 35000,
    oldPrice: 44000,
    off: "-20%",
    stars: "★★★★☆",
    count: 342,
    stock: 45,
    sold: 210,
    blurb: [
      "Charge your phone four to five times from one power bank — essential for load shedding, travel and long days.",
      "Genuine Anker with an 18-month warranty.",
    ],
    highlights: [
      ["Capacity", "20,000mAh (4–5 phone charges)"],
      ["Charging", "20W USB-C fast charge"],
      ["Ports", "USB-C + 2× USB-A"],
      ["Safety", "Anker MultiProtect"],
      ["Warranty", "18 months, genuine Anker"],
    ],
    specs: [
      ["Capacity", "20,000mAh / 72Wh"],
      ["Output", "20W USB-C PD, 18W USB-A"],
      ["Input", "USB-C fast recharge"],
      ["Weight", "343g"],
      ["In the box", "Power bank, USB-C cable, pouch"],
    ],
  },
  {
    slug: "oraimo-freepods-4",
    title: "Oraimo FreePods 4 — Wireless earbuds, 35hr battery",
    brand: "Oraimo",
    category: "audio",
    art: "earbuds",
    price: 28000,
    stars: "★★★★☆",
    count: 521,
    stock: 60,
    sold: 340,
    blurb: [
      "Our best-selling earbuds: clear calls, punchy bass, and 35 hours of total battery with the charging case.",
      "Genuine Oraimo with a 12-month warranty.",
    ],
    highlights: [
      ["Battery", "35 hours total with case"],
      ["Sound", "ENC clear calls, bass boost"],
      ["Comfort", "Lightweight, touch controls"],
      ["Connectivity", "Bluetooth 5.3"],
      ["Warranty", "12 months, genuine Oraimo"],
    ],
    specs: [
      ["Battery", "35h total (case), 7h per charge"],
      ["Bluetooth", "5.3, auto pairing"],
      ["Calls", "4-mic ENC noise cancelling"],
      ["Charging", "USB-C"],
      ["In the box", "Earbuds, case, cable, ear tips"],
    ],
  },
];

export function findProduct(slug) {
  return products.find(function (p) {
    return p.slug === slug;
  });
}

export function byCategory(category) {
  return products.filter(function (p) {
    return p.category === category;
  });
}

export function bySlugs(slugs) {
  return slugs.map(findProduct).filter(Boolean);
}
